### ISSUE TITLE
Question - Group B XML Version

### ISSUE THREAD

**Issue by jrsavs21** [SEARCH-NCJIS/nibrs#12]
The XSD allows for multiple group b arrests per report, but the implementation through this service only accounts for one arrestee.  This results in errors validations that are not correct. For example if you send two group b arrests both with the same armed with, it will throw duplicate arrest weapon error, which is not correct.

Do you know if the FBI is expecting that Group B arrests will always be sent as one arrest per file?  An example would be 3 people arrested for Trespassing, per the XSD they could all be sent at once, but I am not sure what the intent is here. Its somewhat confusing as the Group B Delete example talks about sending multiple numbers.

**Comment by aowen** [comment]
@jrsavs21 even though the XSD allows multiple arrestees in the nibrs:Report node, the NIBRS specification prohibits this (I think the XSD is designed this way to support group A reports).  For group B, the NIBRS spec mentions things like _"One Group B Arrest Report Segment is submitted for each person arrested for committing a Group B offense."_ and _"The Group B Arrest Report Segment does not use Data Element 44 (Multiple Arrestee Segments Indicator)_ . 

This is one of the many rules in the NIBRS spec that isn't enforceable in the NIBRS XSD.  

We will be update the code to return an error if a group B XML submission contains more than one arrestee.

**Comment by jrsavs21** [comment]
Thanks!
